# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projekte\InMoov\servoGui\detailQtGui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServoDetails(object):
    def setupUi(self, ServoDetails):
        ServoDetails.setObjectName("ServoDetails")
        ServoDetails.resize(404, 616)
        ServoDetails.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(ServoDetails)
        self.buttonBox.setGeometry(QtCore.QRect(40, 570, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.Arduino = QtWidgets.QSpinBox(ServoDetails)
        self.Arduino.setGeometry(QtCore.QRect(160, 20, 42, 22))
        self.Arduino.setMaximum(1)
        self.Arduino.setObjectName("Arduino")
        self.LabelArduino = QtWidgets.QLabel(ServoDetails)
        self.LabelArduino.setGeometry(QtCore.QRect(20, 20, 130, 13))
        self.LabelArduino.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelArduino.setObjectName("LabelArduino")
        self.LabelPin = QtWidgets.QLabel(ServoDetails)
        self.LabelPin.setGeometry(QtCore.QRect(20, 50, 130, 13))
        self.LabelPin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin.setObjectName("LabelPin")
        self.Pin = QtWidgets.QSpinBox(ServoDetails)
        self.Pin.setGeometry(QtCore.QRect(160, 50, 42, 22))
        self.Pin.setMaximum(50)
        self.Pin.setObjectName("Pin")
        self.LabelPin_2 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_2.setGeometry(QtCore.QRect(20, 500, 130, 13))
        self.LabelPin_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_2.setObjectName("LabelPin_2")
        self.CableArduinoTerminal = QtWidgets.QLineEdit(ServoDetails)
        self.CableArduinoTerminal.setGeometry(QtCore.QRect(160, 500, 220, 20))
        self.CableArduinoTerminal.setObjectName("CableArduinoTerminal")
        self.LabelPin_3 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_3.setGeometry(QtCore.QRect(20, 80, 130, 13))
        self.LabelPin_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_3.setObjectName("LabelPin_3")
        self.PowerPin = QtWidgets.QSpinBox(ServoDetails)
        self.PowerPin.setGeometry(QtCore.QRect(160, 80, 42, 22))
        self.PowerPin.setMinimum(40)
        self.PowerPin.setMaximum(50)
        self.PowerPin.setObjectName("PowerPin")
        self.LabelPin_4 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_4.setGeometry(QtCore.QRect(20, 140, 130, 13))
        self.LabelPin_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_4.setObjectName("LabelPin_4")
        self.LabelPin_5 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_5.setGeometry(QtCore.QRect(20, 170, 130, 13))
        self.LabelPin_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_5.setObjectName("LabelPin_5")
        self.LabelPin_6 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_6.setGeometry(QtCore.QRect(20, 290, 130, 16))
        self.LabelPin_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_6.setObjectName("LabelPin_6")
        self.LabelPin_7 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_7.setGeometry(QtCore.QRect(20, 320, 130, 20))
        self.LabelPin_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_7.setObjectName("LabelPin_7")
        self.LabelPin_8 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_8.setGeometry(QtCore.QRect(20, 350, 130, 20))
        self.LabelPin_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_8.setObjectName("LabelPin_8")
        self.LabelPin_9 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_9.setGeometry(QtCore.QRect(20, 380, 130, 20))
        self.LabelPin_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_9.setObjectName("LabelPin_9")
        self.LabelPin_10 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_10.setGeometry(QtCore.QRect(20, 410, 130, 13))
        self.LabelPin_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_10.setObjectName("LabelPin_10")
        self.LabelPin_11 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_11.setGeometry(QtCore.QRect(20, 110, 130, 16))
        self.LabelPin_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_11.setObjectName("LabelPin_11")
        self.LabelPin_12 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_12.setGeometry(QtCore.QRect(20, 440, 130, 13))
        self.LabelPin_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_12.setObjectName("LabelPin_12")
        self.LabelPin_13 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_13.setGeometry(QtCore.QRect(20, 470, 130, 13))
        self.LabelPin_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_13.setObjectName("LabelPin_13")
        self.LabelPin_14 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_14.setGeometry(QtCore.QRect(20, 530, 130, 13))
        self.LabelPin_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_14.setObjectName("LabelPin_14")
        self.CableTerminalServo = QtWidgets.QLineEdit(ServoDetails)
        self.CableTerminalServo.setGeometry(QtCore.QRect(160, 530, 220, 20))
        self.CableTerminalServo.setObjectName("CableTerminalServo")
        self.MinComment = QtWidgets.QLineEdit(ServoDetails)
        self.MinComment.setGeometry(QtCore.QRect(160, 140, 220, 20))
        self.MinComment.setObjectName("MinComment")
        self.MaxComment = QtWidgets.QLineEdit(ServoDetails)
        self.MaxComment.setGeometry(QtCore.QRect(160, 170, 220, 20))
        self.MaxComment.setObjectName("MaxComment")
        self.MinDegrees = QtWidgets.QSpinBox(ServoDetails)
        self.MinDegrees.setGeometry(QtCore.QRect(160, 290, 61, 22))
        self.MinDegrees.setMinimum(-120)
        self.MinDegrees.setMaximum(120)
        self.MinDegrees.setProperty("value", -90)
        self.MinDegrees.setObjectName("MinDegrees")
        self.MaxDegrees = QtWidgets.QSpinBox(ServoDetails)
        self.MaxDegrees.setGeometry(QtCore.QRect(160, 320, 61, 22))
        self.MaxDegrees.setMinimum(-120)
        self.MaxDegrees.setMaximum(120)
        self.MaxDegrees.setProperty("value", 90)
        self.MaxDegrees.setObjectName("MaxDegrees")
        self.AutoDetach = QtWidgets.QSpinBox(ServoDetails)
        self.AutoDetach.setGeometry(QtCore.QRect(160, 350, 61, 22))
        self.AutoDetach.setMinimum(1000)
        self.AutoDetach.setMaximum(10000)
        self.AutoDetach.setSingleStep(500)
        self.AutoDetach.setProperty("value", 2000)
        self.AutoDetach.setObjectName("AutoDetach")
        self.RestDegrees = QtWidgets.QSpinBox(ServoDetails)
        self.RestDegrees.setGeometry(QtCore.QRect(160, 410, 42, 22))
        self.RestDegrees.setMinimum(-120)
        self.RestDegrees.setMaximum(120)
        self.RestDegrees.setObjectName("RestDegrees")
        self.Inverted = QtWidgets.QCheckBox(ServoDetails)
        self.Inverted.setGeometry(QtCore.QRect(160, 380, 70, 17))
        self.Inverted.setText("")
        self.Inverted.setObjectName("Inverted")
        self.Enabled = QtWidgets.QCheckBox(ServoDetails)
        self.Enabled.setGeometry(QtCore.QRect(160, 110, 70, 17))
        self.Enabled.setText("")
        self.Enabled.setObjectName("Enabled")
        self.ServoType = QtWidgets.QComboBox(ServoDetails)
        self.ServoType.setGeometry(QtCore.QRect(160, 440, 220, 22))
        self.ServoType.setObjectName("ServoType")
        self.TerminalSlot = QtWidgets.QSpinBox(ServoDetails)
        self.TerminalSlot.setGeometry(QtCore.QRect(160, 470, 42, 22))
        self.TerminalSlot.setMinimum(1)
        self.TerminalSlot.setMaximum(20)
        self.TerminalSlot.setProperty("value", 1)
        self.TerminalSlot.setObjectName("TerminalSlot")
        self.MinPos = QtWidgets.QSpinBox(ServoDetails)
        self.MinPos.setGeometry(QtCore.QRect(160, 200, 61, 22))
        self.MinPos.setMinimum(0)
        self.MinPos.setMaximum(180)
        self.MinPos.setProperty("value", 0)
        self.MinPos.setObjectName("MinPos")
        self.ZeroDegPos = QtWidgets.QSpinBox(ServoDetails)
        self.ZeroDegPos.setGeometry(QtCore.QRect(160, 260, 61, 22))
        self.ZeroDegPos.setMinimum(0)
        self.ZeroDegPos.setMaximum(180)
        self.ZeroDegPos.setSingleStep(1)
        self.ZeroDegPos.setProperty("value", 90)
        self.ZeroDegPos.setObjectName("ZeroDegPos")
        self.LabelPin_15 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_15.setGeometry(QtCore.QRect(20, 200, 130, 16))
        self.LabelPin_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_15.setObjectName("LabelPin_15")
        self.LabelPin_16 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_16.setGeometry(QtCore.QRect(20, 230, 130, 20))
        self.LabelPin_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_16.setObjectName("LabelPin_16")
        self.LabelPin_17 = QtWidgets.QLabel(ServoDetails)
        self.LabelPin_17.setGeometry(QtCore.QRect(20, 260, 130, 20))
        self.LabelPin_17.setTextFormat(QtCore.Qt.RichText)
        self.LabelPin_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelPin_17.setObjectName("LabelPin_17")
        self.MaxPos = QtWidgets.QSpinBox(ServoDetails)
        self.MaxPos.setGeometry(QtCore.QRect(160, 230, 61, 22))
        self.MaxPos.setMinimum(0)
        self.MaxPos.setMaximum(180)
        self.MaxPos.setProperty("value", 180)
        self.MaxPos.setObjectName("MaxPos")

        self.retranslateUi(ServoDetails)
        self.buttonBox.accepted.connect(ServoDetails.accept)
        self.buttonBox.rejected.connect(ServoDetails.reject)
        QtCore.QMetaObject.connectSlotsByName(ServoDetails)

    def retranslateUi(self, ServoDetails):
        _translate = QtCore.QCoreApplication.translate
        ServoDetails.setWindowTitle(_translate("ServoDetails", "Dialog"))
        self.LabelArduino.setText(_translate("ServoDetails", "Arduino:"))
        self.LabelPin.setText(_translate("ServoDetails", "Pin:"))
        self.LabelPin_2.setText(_translate("ServoDetails", "Cable Arduino->Terminal:"))
        self.LabelPin_3.setText(_translate("ServoDetails", "Power Pin:"))
        self.LabelPin_4.setText(_translate("ServoDetails", "Min Comment:"))
        self.LabelPin_5.setText(_translate("ServoDetails", "Max Comment:"))
        self.LabelPin_6.setText(_translate("ServoDetails", "Min Degrees:"))
        self.LabelPin_7.setText(_translate("ServoDetails", "Max Degrees:"))
        self.LabelPin_8.setText(_translate("ServoDetails", "Auto Detach:"))
        self.LabelPin_9.setText(_translate("ServoDetails", "Inverted:"))
        self.LabelPin_10.setText(_translate("ServoDetails", "Rest Degrees:"))
        self.LabelPin_11.setText(_translate("ServoDetails", "Enabled:"))
        self.LabelPin_12.setText(_translate("ServoDetails", "Servo Type:"))
        self.LabelPin_13.setText(_translate("ServoDetails", "Cable Terminal Slot:"))
        self.LabelPin_14.setText(_translate("ServoDetails", "Cable Terminal->Servo:"))
        self.LabelPin_15.setText(_translate("ServoDetails", "Min Pos:"))
        self.LabelPin_16.setText(_translate("ServoDetails", "Max Pos:"))
        self.LabelPin_17.setText(_translate("ServoDetails", "Zero Degrees Pos:"))


